repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: bash -c 'unformatted=$(gofmt -l "$@"); if [ -n "$unformatted" ]; then echo "$unformatted"; exit 1; fi' --
        language: system
        types: [go]
        exclude: ^web/

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
        exclude: ^web/

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
        exclude: ^web/
